swagger: "2.0"
info:
  version: 1.0.0
  title: Test API
  description: Test API.
host: localhost
basePath: /api/v1
schemes:
  - https
securityDefinitions:
  bearerToken:
    type: apiKey
    name: Authorization
    in: header
paths:
  /test-auth-bearer:
    get:
      operationId: "testAuthBearer"
      security:
        - bearerToken: []
      parameters:
        - name: "qo"
          in: "query"
          required: false
          type: "string"
        - name: "qr"
          in: "query"
          required: true
          type: "string"
        - $ref: "#/parameters/PaginationRequest"
      responses:
        "200":
          description: "Will send `Authenticated`"
        "403":
          description: "You do not have necessary permissions for the resource"
  /test-multiple-success:
    get:
      operationId: "testMultipleSuccess"
      responses:
        "200":
          description: "Will return a Message"
          schema:
            $ref: "#/definitions/Message"
        "202":
          description: "Will return just accepted"
        "403":
          description: "You do not have necessary permissions for the resource"
          schema:
            $ref: "#/definitions/OneOfTest"
        "404":
          description: "Not found"

  /test-file-upload:
    post:
      operationId: "testFileUpload"
      consumes:
        - multipart/form-data
      parameters:
        - name: "file"
          in: "formData"
          type: "file"
          required: true
      responses:
        "200":
          description: "File uploaded"
  /test-response-header:
    get:
      operationId: "testResponseHeader"
      responses:
        "201":
          description: "Will create a Message"
          schema:
            $ref: "#/definitions/Message"
          headers:
            Location:
              type: string
            Id:
              type: string
        "500":
          description: "Fatal error"
definitions:
  Person:
    $ref: "definitions.yaml#/Person"
  Book:
    $ref: "definitions.yaml#/Book"        
  AllOfTest:
    allOf:
      - type: object
        properties:
          items:
            type: array
            items:
              $ref: "#/definitions/Message"
      - $ref: "#/definitions/PaginationResponse"
  AllOfOneOfTest:
    description: test if we can use allOf as oneOf
    x-one-of: true
    allOf:
      - type: object
        properties:
          items:
            type: array
            items:
              $ref: "#/definitions/Message"
      - $ref: "#/definitions/PaginationResponse"
  OneOfTest:
    oneOf:
      - type: object
        properties:
          limited:
            type: boolean
      - type: object
        properties:
          unlimited:
            type: boolean
  AdditionalPropsTest:
    type: object
    additionalProperties:
      type: array
      items:
        type: number
  AdditionalpropsDefault:
    type: object
    default: { "test": [1000] }
    additionalProperties:
      type: array
      items:
        type: number
  AdditionalPropsTrueTest:
    type: object
    additionalProperties: true
  NonNegativeNumberTest:
    title: NonNegativeNumberTest
    type: number
    minimum: 0
  WithinRangeStringTest:
    title: WithinRangeStringTest
    type: string
    minLength: 10
    maxLength: 10
  WithinRangeNumberTest:
    title: WithinRangeNumberTest
    type: number
    minimum: 0
    maximum: 10
  InlinePropertyTest:
    type: object
    properties:
      inlineProp:
        type: string
        description: The device global unique identifier.
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  CustomStringFormatTest:
    type: string
    x-import: italia-ts-commons/lib/strings
    format: SomeCustomStringType
  OrganizationFiscalCode:
    type: string
    x-import: italia-ts-commons/lib/strings
    format: OrganizationFiscalCode
  OrganizationFiscalCodeTest:
    type: string
    x-import: italia-ts-commons/lib/strings
    format: OrganizationFiscalCode
  NonNegativeIntegerTest:
    title: NonNegativeIntegerTest
    type: integer
    minimum: 0
  WithinRangeIntegerTest:
    title: WithinRangeIntegerTest
    type: integer
    minimum: 0
    maximum: 10
  NestedObjectTest:
    type: object
    properties:
      inlineProp:
        type: string
        description: The device global unique identifier.
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
      nestedObject:
        type: object
        properties:
          inlineProp:
            type: string
            description: The device global unique identifier.
            pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
  EnumTest:
    type: object
    properties:
      status:
        type: string
        enum:
          - value1
          - value2
          - value3
  MessageContent:
    type: object
    properties:
      subject:
        $ref: "#/definitions/MessageSubject"
      markdown:
        $ref: "#/definitions/MessageBodyMarkdown"
    required:
      - markdown
  MessageSubject:
    type: string
    description: |-
      The (optional) subject of the message - note that only some notification
      channels support the display of a subject. When a subject is not provided,
      one gets generated from the client attributes.
    minLength: 10
    maxLength: 120
    example: Welcome new user !
  MessageBodyMarkdown:
    type: string
    description: |-
      The full version of the message, in plain text or Markdown format. The
      content of this field will be delivered to channels that don't have any
      limit in terms of content size (e.g. email, etc...).
    minLength: 80
    maxLength: 10000
    example: |-
      # This is a markdown header

      to show how easily markdown can be converted to **HTML**

      Remember: this has to be a long text.
  FiscalCode:   
    type: string
    description: User's fiscal code.
    pattern: "^[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]$"
    example: SPNDNL80R13C555X
  EmailAddress:
    type: string
    format: email
    example: foobar@example.com
  ExtendedProfile:
    description: Describes the citizen's profile, mostly interesting for preferences attributes.
    type: object
    properties:
      email:
        $ref: "#/definitions/EmailAddress"
      preferred_languages:
        $ref: "#/definitions/PreferredLanguages"
      is_inbox_enabled:
        $ref: "#/definitions/IsInboxEnabled"
      is_webhook_enabled:
        $ref: "#/definitions/IsWebhookEnabled"
      version:
        type: integer
  LimitedProfile:
    description: Describes the citizen's profile, mostly interesting for preferences attributes.
    type: object
    properties:
      preferred_languages:
        $ref: "#/definitions/PreferredLanguages"
  PreferredLanguages:
    type: array
    items:
      $ref: "#/definitions/PreferredLanguage"
    description: Indicates the User's preferred written or spoken languages in order
      of preference. Generally used for selecting a localized User interface. Valid
      values are concatenation of the ISO 639-1 two letter language code, an underscore,
      and the ISO 3166-1 2 letter country code; e.g., 'en_US' specifies the language
      English and country US.
  PreferredLanguage:
    type: string
    x-extensible-enum:
      - it_IT
      - en_GB
      - es_ES
      - de_DE
      - fr_FR
    example: it_IT
  IsInboxEnabled:
    type: boolean
    default: false
    description: True if the recipient of a message wants to store its content for
      later retrieval.
  IsWebhookEnabled:
    type: boolean
    default: false
    description: True if the recipient of a message wants to forward the notifications to the default webhook.
  PaginationResponse:
    type: object
    description: Pagination response parameters.
    properties:
      page_size:
        type: integer
        minimum: 1
        description: Number of items returned for each page.
        example: 2
      next:
        type: string
        description: 'Contains an URL to GET the next #<page_size> results in the
          retrieved collection of items.'
        format: uri
        example: https://example.com/?p=0XXX2
  CreatedMessageWithContent:
    type: object
    properties:
      id:
        type: string
      fiscal_code:
        $ref: "#/definitions/FiscalCode"
      time_to_live:
        $ref: "#/definitions/TimeToLiveSeconds"
      content:
        $ref: "#/definitions/MessageContent"
      sender_service_id:
        type: string
    required:
      - fiscal_code
      - sender_service_id
  TimeToLiveSeconds:
    type: integer
    default: 3600
    minimum: 3600
    maximum: 604800
    description: This parameter specifies for how long (in seconds) the system will
      try to deliver the message to the channels configured by the user.
    example: 3600
  ServicePublic:
    title: Service (public)
    description: A Service associated to an user's subscription.
    type: object
    properties:
      service_id:
        $ref: "#/definitions/ServiceId"
      service_name:
        $ref: "#/definitions/ServiceName"
      organization_name:
        $ref: "#/definitions/OrganizationName"
      department_name:
        $ref: "#/definitions/DepartmentName"
      version:
        type: integer
    required:
      - service_id
      - service_name
      - organization_name
      - department_name
  ServiceId:
    type: string
    description: The ID of the Service. Equals the subscriptionId of a registered
      API user.
    minLength: 1
  ServiceName:
    type: string
    description: The name of the service. Will be added to the content of sent messages.
    minLength: 1
  OrganizationName:
    type: string
    description: The organization that runs the service. Will be added to the content
      of sent messages to identify the sender.
    minLength: 1
  DepartmentName:
    type: string
    description: The department inside the organization that runs the service. Will
      be added to the content of sent messages.
    minLength: 1
  Message:
    title: Message
    type: object
    properties:
      id:
        type: string
      content:
        $ref: "#/definitions/MessageContent"
      sender_service_id:
        type: string
    required:
      - id
      - content
  Profile:
    title: Profile
    description: Describes the user's profile.
    type: object
    properties:
      email:
        $ref: "#/definitions/EmailAddress"
      family_name:
        type: string
      fiscal_code:
        $ref: "#/definitions/FiscalCode"
      has_profile:
        type: boolean
      is_email_set:
        type: boolean
      is_inbox_enabled:
        $ref: "#/definitions/IsInboxEnabled"
      is_webhook_enabled:
        $ref: "#/definitions/IsWebhookEnabled"
      name:
        type: string
      preferred_email:
        $ref: "#/definitions/EmailAddress"
      preferred_languages:
        $ref: "#/definitions/PreferredLanguages"
      version:
        type: integer
      payload:
        type: object
        properties: {}
    required:
      - fiscal_code
      - family_name
      - has_profile
      - is_email_set
      - name
      - version
responses: {}
parameters:
  PaginationRequest:
    name: cursor
    in: query
    type: string
    minimum: 1
    description: An opaque identifier that points to the next item in the collection.
consumes:
  - application/json
produces:
  - application/json
